export const sampleData = [
  {
    id: 1,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'VentureStrat Associates...',
    founderYear: '2020',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Run condition not met',
    phoneNumber: '+(91) 96520 27845',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 2,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Work From Home/ Fresh...',
    founderYear: '2019',
    findIcp: 'NON - ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 98765 43210',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 3,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'TechCorp Solutions...',
    founderYear: '2021',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Run condition not met',
    phoneNumber: '+(91) 87654 32109',
    fetchPhoneNumber: 'No contact found'
  },
  {
    id: 4,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Innovation Labs...',
    founderYear: '2018',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 76543 21098',
    fetchPhoneNumber: 'No contact found'
  },
  {
    id: 5,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Digital Dynamics...',
    founderYear: '2022',
    findIcp: 'NON - ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Run condition not met',
    phoneNumber: '+(91) 65432 10987',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 6,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'FutureTech Systems...',
    founderYear: '2020',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 54321 09876',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 7,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Smart Solutions...',
    founderYear: '2021',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 43210 98765',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 8,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'NextGen Technologies...',
    founderYear: '2019',
    findIcp: 'NON - ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Run condition not met',
    phoneNumber: '+(91) 32109 87654',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 9,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Cloud Computing Corp...',
    founderYear: '2020',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Run condition not met',
    phoneNumber: '+(91) 21098 76543',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 10,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'AI Innovations...',
    founderYear: '2021',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 10987 65432',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 11,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Data Analytics Pro...',
    founderYear: '2022',
    findIcp: 'NON - ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 09876 54321',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 12,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Mobile App Studio...',
    founderYear: '2020',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Run condition not met',
    phoneNumber: '+(91) 98765 43210',
    fetchPhoneNumber: 'No contact found'
  },
  {
    id: 13,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Web Development Hub...',
    founderYear: '2021',
    findIcp: 'ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 87654 32109',
    fetchPhoneNumber: 'Response'
  },
  {
    id: 14,
    source: 'Bill Gates',
    lastUpdatedAt: 'Oct 12, 2024 at 14:08 PM',
    companyName: 'Cybersecurity Plus...',
    founderYear: '2019',
    findIcp: 'NON - ICP',
    linkedinJobUrl: 'https://www.linkedin.co...',
    waterfallPeople: 'Bitscale Evaluation...',
    phoneNumber: '+(91) 76543 21098',
    fetchPhoneNumber: 'Response'
  }
]; 